"""add_suite_login_config

Revision ID: c0eddf2d26cd
Revises: 106ba460b93b
Create Date: 2026-04-06 16:44:24.714846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0eddf2d26cd'
down_revision: Union[str, Sequence[str], None] = '106ba460b93b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_suites', sa.Column('login_url', sa.String(length=500), nullable=True))
    op.add_column('test_suites', sa.Column('login_email', sa.String(length=200), nullable=True))
    op.add_column('test_suites', sa.Column('login_password', sa.Text(), nullable=True))
    op.add_column('test_suites', sa.Column('storage_state_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_suites', 'storage_state_json')
    op.drop_column('test_suites', 'login_password')
    op.drop_column('test_suites', 'login_email')
    op.drop_column('test_suites', 'login_url')
    # ### end Alembic commands ###
